from django.db import models

# Create your models here.

class UserFeature(models.Model):
    user_id = models.AutoField(db_column = 'user_id', primary_key=True)
    user_ip = models.GenericIPAddressField()
    time_stamp = models.DateTimeField(auto_now_add=True)
    solo = models.PositiveSmallIntegerField(default=0)
    couple = models.PositiveSmallIntegerField(default=0)
    family = models.PositiveSmallIntegerField(default=0)
    friends = models.PositiveSmallIntegerField(default=0)
    mid_week = models.PositiveSmallIntegerField(default=0)
    weekend = models.PositiveSmallIntegerField(default=0)
    long_weekend = models.PositiveSmallIntegerField(default=0)
    weekish = models.PositiveSmallIntegerField(default=0)
    two_weeks = models.PositiveSmallIntegerField(db_column='2_weeks',default=0)
    three_weeks = models.PositiveSmallIntegerField(db_column='3_weeks',default=0)
    four_weeks = models.PositiveSmallIntegerField(db_column='4_weeks',default=0)
    beach = models.PositiveSmallIntegerField(default=0)
    city_life = models.PositiveSmallIntegerField(default=0)
    nature = models.PositiveSmallIntegerField(default=0)
    countryside = models.PositiveSmallIntegerField(default=0)
    surprise = models.PositiveSmallIntegerField(default=0)
    other = models.PositiveSmallIntegerField(default=0)
    adventures = models.PositiveSmallIntegerField(default=0)
    shopping = models.PositiveSmallIntegerField(default=0)
    romantic = models.PositiveSmallIntegerField(default=0)
    ski = models.PositiveSmallIntegerField(default=0)
    remote = models.PositiveSmallIntegerField(default=0)
    wildlife = models.PositiveSmallIntegerField(default=0)
    hiking = models.PositiveSmallIntegerField(default=0)
    road_trip = models.PositiveSmallIntegerField(default=0)
    festivals = models.PositiveSmallIntegerField(default=0)
    nightlife = models.PositiveSmallIntegerField(default=0)
    holidays = models.PositiveSmallIntegerField(default=0)
    vivid = models.PositiveSmallIntegerField(default=0)
    cultural_experience = models.PositiveSmallIntegerField(default=0)
    camping = models.PositiveSmallIntegerField(default=0)
    surfing = models.PositiveSmallIntegerField(default=0)
    honeymoon = models.PositiveSmallIntegerField(default=0)
    scuba_diving = models.PositiveSmallIntegerField(default=0)
    budget_low = models.PositiveSmallIntegerField(default=0)
    budget_normal = models.PositiveSmallIntegerField(default=0)
    budget_high = models.PositiveSmallIntegerField(default=0)
    one_passengers = models.PositiveSmallIntegerField(db_column='1_passengers',default=0)
    two_passengers = models.PositiveSmallIntegerField(db_column='2_passengers',default=0)
    three_passengers = models.PositiveSmallIntegerField(db_column='3_passengers',default=0)
    four_passengers = models.PositiveSmallIntegerField(db_column='4_passengers',default=0)
    five_passengers = models.PositiveSmallIntegerField(db_column='5_passengers',default=0)
    six_passengers = models.PositiveSmallIntegerField(db_column='6_passengers',default=0)
    january = models.PositiveSmallIntegerField(default=0)
    february = models.PositiveSmallIntegerField(default=0)
    march = models.PositiveSmallIntegerField(default=0)
    april = models.PositiveSmallIntegerField(default=0)
    may = models.PositiveSmallIntegerField(default=0)
    june = models.PositiveSmallIntegerField(default=0)
    july = models.PositiveSmallIntegerField(default=0)
    august = models.PositiveSmallIntegerField(default=0)
    september = models.PositiveSmallIntegerField(default=0)
    october = models.PositiveSmallIntegerField(default=0)
    november = models.PositiveSmallIntegerField(default=0)
    december = models.PositiveSmallIntegerField(default=0)
    comp_allgirls = models.PositiveSmallIntegerField(default=0)
    comp_allboys = models.PositiveSmallIntegerField(default=0)
    comp_elderly = models.PositiveSmallIntegerField(default=0)
    comp_kids_babies = models.PositiveSmallIntegerField(default=0)

    class Meta:
        db_table = "users_features"

class CityFeature(models.Model):
    city_id = models.AutoField(db_column = 'city_id',primary_key=True)
    city_name = models.CharField(max_length = 40)
    country = models.CharField(max_length = 40)
    short_description = models.CharField(max_length = 400)
    sites = models.CharField(max_length = 400)
    picture = models.CharField(max_length = 400)
    solo = models.PositiveSmallIntegerField(default=0)
    couple = models.PositiveSmallIntegerField(default=0)
    family = models.PositiveSmallIntegerField(default=0)
    friends = models.PositiveSmallIntegerField(default=0)
    mid_week = models.PositiveSmallIntegerField(default=0)
    weekend = models.PositiveSmallIntegerField(default=0)
    long_weekend = models.PositiveSmallIntegerField(default=0)
    weekish = models.PositiveSmallIntegerField(default=0)
    two_weeks = models.PositiveSmallIntegerField(db_column='2_weeks',default=0)
    three_weeks = models.PositiveSmallIntegerField(db_column='3_weeks',default=0)
    four_weeks = models.PositiveSmallIntegerField(db_column='4_weeks',default=0)
    beach = models.PositiveSmallIntegerField(default=0)
    city_life = models.PositiveSmallIntegerField(default=0)
    nature = models.PositiveSmallIntegerField(default=0)
    countryside = models.PositiveSmallIntegerField(default=0)
    surprise = models.PositiveSmallIntegerField(default=0)
    other = models.PositiveSmallIntegerField(default=0)
    adventures = models.PositiveSmallIntegerField(default=0)
    shopping = models.PositiveSmallIntegerField(default=0)
    romantic = models.PositiveSmallIntegerField(default=0)
    ski = models.PositiveSmallIntegerField(default=0)
    remote = models.PositiveSmallIntegerField(default=0)
    wildlife = models.PositiveSmallIntegerField(default=0)
    hiking = models.PositiveSmallIntegerField(default=0)
    road_trip = models.PositiveSmallIntegerField(default=0)
    festivals = models.PositiveSmallIntegerField(default=0)
    nightlife = models.PositiveSmallIntegerField(default=0)
    holidays = models.PositiveSmallIntegerField(default=0)
    vivid = models.PositiveSmallIntegerField(default=0)
    cultural_experience = models.PositiveSmallIntegerField(default=0)
    camping = models.PositiveSmallIntegerField(default=0)
    surfing = models.PositiveSmallIntegerField(default=0)
    honeymoon = models.PositiveSmallIntegerField(default=0)
    scuba_diving = models.PositiveSmallIntegerField(default=0)
    budget_low = models.PositiveSmallIntegerField(default=0)
    budget_normal = models.PositiveSmallIntegerField(default=0)
    budget_high = models.PositiveSmallIntegerField(default=0)
    one_passengers = models.PositiveSmallIntegerField(db_column='1_passengers',default=0)
    two_passengers = models.PositiveSmallIntegerField(db_column='2_passengers',default=0)
    three_passengers = models.PositiveSmallIntegerField(db_column='3_passengers',default=0)
    four_passengers = models.PositiveSmallIntegerField(db_column='4_passengers',default=0)
    five_passengers = models.PositiveSmallIntegerField(db_column='5_passengers',default=0)
    six_passengers = models.PositiveSmallIntegerField(db_column='6_passengers',default=0)
    january = models.PositiveSmallIntegerField(default=0)
    february = models.PositiveSmallIntegerField(default=0)
    march = models.PositiveSmallIntegerField(default=0)
    april = models.PositiveSmallIntegerField(default=0)
    may = models.PositiveSmallIntegerField(default=0)
    june = models.PositiveSmallIntegerField(default=0)
    july = models.PositiveSmallIntegerField(default=0)
    august = models.PositiveSmallIntegerField(default=0)
    september = models.PositiveSmallIntegerField(default=0)
    october = models.PositiveSmallIntegerField(default=0)
    november = models.PositiveSmallIntegerField(default=0)
    december = models.PositiveSmallIntegerField(default=0)
    comp_allgirls = models.PositiveSmallIntegerField(default=0)
    comp_allboys = models.PositiveSmallIntegerField(default=0)
    comp_elderly = models.PositiveSmallIntegerField(default=0)
    comp_kids_babies = models.PositiveSmallIntegerField(default=0)

    class Meta:
        db_table = "cities_features"

class UserCity (models.Model):
    user_id = models.IntegerField()
    city_name = models.CharField(max_length = 150)
    matching_score = models.IntegerField()
    users_rating = models.IntegerField()

    #Metadata
    class Meta:
        db_table = "user_cities_matching"