# Generated by Django 2.2.10 on 2021-04-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=10)),
                ('theme', models.CharField(max_length=150)),
                ('period', models.CharField(max_length=150)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
    ]
