# Generated by Django 2.2.10 on 2021-04-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vacation',
            table='vacation_reglist',
        ),
    ]
