# Generated by Django 2.2.10 on 2021-04-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_auto_20210409_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='object',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='period',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='theme',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
