# Generated by Django 2.2.10 on 2021-05-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0004_auto_20210514_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='comp_alboys',
            new_name='comp_allboys',
        ),
        migrations.AddField(
            model_name='user',
            name='scuba_diving',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
